### ISSUE TITLE
scipy imread 

### ISSUE THREAD

**Issue by Binbose** [BenevolentAI/guacamol#6]
I installed guacamol on a blank new conda environment, with only rdkit and pytorch preinstalled. Guacamol was therefore installing scipy. However, the scipy version guacamol is installing doesn't have the imread function anymore (removed since scipy 1.2, guacamole installs 1.4.1).
Simply removing the import of imread in FCD.py line 24 seems to fix the problem, as the functions is not used in the whole file.

**Comment by avaucher** [comment]
Thanks for reporting this!

The corresponding file comes from the [FCD](https://pypi.org/project/FCD/) package. They fixed the error you are reporting recently and updated the version of the package a few days ago. 

The requirements in guacamol have been updated accordingly and it should be working fine now.
